name: ml2dac_experiments
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jedi=0.19.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.24
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.1.3
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.1
  - readline=8.2
  - six=1.16.0
  - stack_data=0.6.2
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.10.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - wcwidth=0.2.6
  - wheel=0.41.2
  - xz=5.2.6
  - zeromq=4.3.4
  - zipp=3.17.0
  - pip:
      - arrow==1.2.3
      - attrs==23.1.0
      - boto3==1.28.52
      - botocore==1.31.53
      - bravado==11.0.3
      - bravado-core==6.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - configspace==0.6.0
      - cycler==0.11.0
      - cython==0.29.36
      - dask==2023.9.2
      - definitions==0.2.0
      - distributed==2023.9.2
      - emcee==3.1.4
      - fqdn==1.5.1
      - fsspec==2023.9.2
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.37
      - hdbscan==0.8.32
      - idna==3.4
      - isoduration==20.11.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.0.0
      - jsonpointer==2.4
      - jsonref==1.1.0
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.5
      - locket==1.0.0
      - markupsafe==2.1.3
      - matplotlib==3.3.1
      - monotonic==1.6
      - msgpack==1.0.6
      - neptune==1.6.3
      - numpy==1.22.4
      - oauthlib==3.2.2
      - pandas==1.1.5
      - partd==1.4.0
      - patsy==0.5.3
      - pillow==10.0.1
      - pyclustering==0.10.1.2
      - pyjwt==2.8.0
      - pymfe==0.4.1
      - pynisher==0.6.4
      - pyparsing==3.1.1
      - pyrfr==0.9.0
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rpds-py==0.10.3
      - s3transfer==0.6.2
      - scikit-learn==1.0.1
      - scipy==1.8.0
      - seaborn==0.11.2
      - setuptools==49.2.1
      - simplejson==3.19.1
      - smac==1.4.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - statsmodels==0.14.0
      - swagger-spec-validator==3.0.3
      - tblib==2.0.0
      - texttable==1.6.7
      - toolz==0.12.0
      - tqdm==4.66.1
      - uri-template==1.3.0
      - urllib3==1.26.16
      - webcolors==1.13
      - websocket-client==1.6.3
      - zict==3.0.0

